fix cicd healthcheck port

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -79,15 +79,12 @@ jobs:
             docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:staging
             docker rm -f app-staging || true
             docker run -d -p 8081:80 --name app-staging ${{ secrets.DOCKER_USERNAME }}/devops-app:staging
-<<<<<<< HEAD
-=======
             
             # ✅ HEALTHCHECK
             echo "Waiting app to start..."
             sleep 5
 
             curl -f http://localhost:8081 || (echo "Healthcheck FAILED STAGING" && exit 1)
->>>>>>> dev
 
 
   deploy-prod:
@@ -111,4 +108,4 @@ jobs:
             echo "Waiting app to start..."
             sleep 5
 
-            curl -f http://localhost:80 || (echo "Healthcheck FAILED PROD" && exit 1)
+            curl -f http://localhost:8082 || (echo "Healthcheck FAILED PROD" && exit 1)
